### ISSUE TITLE
[BUG] Import-command didn't throw any error message when it failed.

### ISSUE THREAD

**Issue by trandangtri** [ongr-io/Demo#154]
Now, the import command runs in silent. It won't throw any error message/exception when it failed. This problem occurred in all import-commands, including product, category and content.

**Version**: dev-master

**Comment by asev** [comment]
Hello.
Are you talking about invalid data problems (string instead of integer and etc)? In this case, yes you are right.
Commit method does not check the output in [0.10](https://github.com/ongr-io/ElasticsearchBundle/blob/v0.10/Client/Connection.php) and neither in [alpha releases](https://github.com/ongr-io/ElasticsearchBundle/blob/v1.0.0-alpha.4/Service/Manager.php#L364). So you won't see any warning not only at import, but for all bulk operations.
But I don't think it's a bug. It's more like a feature request for [ongr-io/ElasticsearchBundle](https://github.com/ongr-io/ElasticsearchBundle). To have a way to track bulk operation errors.

**Comment by murnieza** [comment]
Yes. That's definitely a problem in ESB. Errors from bulk should be at least logged. Feel free to close this issue and reopen it in correct bundle.

**Comment by trandangtri** [comment]
Yeah, maybe you're right. This issue should be in https://github.com/ongr-io/ElasticsearchBundle. 
I will close this issue here. Please continue to follow this at https://github.com/ongr-io/ElasticsearchBundle/issues/482

Thanks all guys.
